#!/bin/bash
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/liblbfgs-1.10/lib/.libs/
read -p "Enter source, mode, crossV, cold, minTopic, maxTopic:" source mode crossV cold min max
echo 
for (( k = $min; k <= $max; k = k + 10 ))
do
    ./train -dir /zf18/ll5fy/lab/dataset -source $source -mode $mode -crossV $crossV -cold $cold -K $k -iter 50 > ./output/"$crossV"_"$cold"_"$source"_HFT_"$mode"_"$k".output
done
